import copy 
import pygame 

from utils     import limit, constrain, derivativeBivariate
from constants import *

class Drone():
    def __init__(self, x, y, index):
        """
            Idealized class representing a drone
            :param x and y: represents inicial position 
        """
        # Variables used to move drone 
        self.location = pygame.math.Vector2(x,y) 
        self.velocity = pygame.math.Vector2(0,0) 
        self.acceleration = pygame.math.Vector2(0,0)
        self.target = SCREEN_WIDTH
        self.radius = SIZE_DRONE            
        self.desired = pygame.math.Vector2()
        self.reached = False
        self.alive = True

        # Arbitrary values
        self.max_speed = FORWARD_SPEED
        self.max_force = SEEK_FORCE

        # Variables related to State Machine
        self.theta = 0 # variavel para o eight somada no seek_around
        self.count = 0
        self.id = index
        self.name = "Drone " + str(index)
        self.time_executing = 0  
        self.finished = False

        # State variables
        self.neighbors = pygame.math.Vector2()
        self.obstacles = pygame.math.Vector2()
        self.vulnerability = 0
        self.connectivity = 0


    def reached_goal(self):
        self.reached = self.target - self.location[0] <= THRESHOLD_TARGET
        return self.reached


    def applyForce(self, force):
        self.acceleration += force/MASS 


    def execute(self, action, enable_target=True):
        """
            Execute action
            Suffer effects from the environment
        """
        self.time_executing += 1
        # updates behavior in machine state
        if enable_target: 
            self.arrive(self.target)
        # Updates velocity at every step and limits it to max_speed
        self.velocity += self.acceleration 
        self.velocity = limit(self.velocity, self.max_speed)
        # Updates position
        self.location += (self.velocity + action) 
        # Constrains position to limits of screen 
        self.location = constrain(self.location, SCREEN_WIDTH, SCREEN_HEIGHT)
        self.acceleration *= 0
        # Print if drone reached destination
        #if not self.reached and self.reached_goal():
        #    print(f"{self.name} reached target")

        if (self.target - self.location[0]) < THRESHOLD_TARGET and self.time_executing < 300:
            self.finished = True


    def arrive(self, target):
        """
            Arrive Steering Behavior
        """
        # Calculates vector desired 
        v = pygame.math.Vector2([target - self.location[0], 0])
        # get the distance to the target
        distance = v.magnitude() 
        direction = pygame.math.Vector2(1,0)
        
        # Modulates the force
        if distance < THRESHOLD_TARGET : 
            # close to target it will reduce velocty till stops
            direction *= self.max_speed*(1 + 1/THRESHOLD_TARGET*(distance-THRESHOLD_TARGET))
        else:
            direction *= self.max_speed

        # Steering force
        steer = direction - self.velocity
        # Limit the magnitude of the steering force.
        #steer = limit(steer, self.max_force)
        # Apply force to the Drone
        self.applyForce(steer)


    def scan_neighbors(self, positions):
        """
         This method scans for neighbors CM and gets it's direction
         During training it receives all the positions from all drones 
         During evaluation it receives only the positions inside observable area 
        """
        # Calculate potential generated by topology while removing the current drone
        v = pygame.math.Vector2(0,0) 
        for position in positions:
            distance = (position - self.location).magnitude()
            if 0 < distance < OBSERVABLE_RADIUS:
                # Get normalized direction of neighbor 
                direction = (position - self.location).normalize() 
                # Proporcional to the distance. The closer the stronger needs to be
                direction = direction / distance 
                v += direction

        if v == pygame.math.Vector2(0,0):
            self.neighbors = pygame.math.Vector2(0,0) 
            return 
 
        # This gives the direction of the resulting potential 
        self.neighbors = v.normalize()
                  

    def scan_obstacles(self, positions):
        """
         This method scans for obstacles CM and gets it's direction
         During training it receives all the positions from all obstacles 
         During evaluation it receives only the positions inside observable area 
        """
        # Calculate potential generated by obstacles
        v = pygame.math.Vector2(0,0) 
        for position in positions:
            distance = (position - self.location).magnitude()
            if 0 < distance < OBSERVABLE_RADIUS:
                # Get normalized direction of neighbor 
                direction = (position - self.location).normalize() 
                # Proporcional to the distance. The closer the stronger needs to be
                direction = direction / distance 
                v += direction

        if v == pygame.math.Vector2(0,0):
            self.obstacles = pygame.math.Vector2(0,0) 
            return 

        # This gives the direction of the resulting potential 
        self.obstacles = v.normalize()


    def calculate_potential_field(self, pos_drones, pos_obstacles):
        """
            Determine resulting potential field given obstacles and other drones
        """
        # Repulsion drones
        for position in pos_drones:
            distance = (self.location - position).magnitude()
            if 0 < distance < 2 * AVOID_DISTANCE:
                f_repulsion = derivativeBivariate(0.001, 0.001, position, self.location) / SAMPLE_TIME
                f_repulsion = limit(f_repulsion, self.max_force*1.8)
                self.applyForce(-f_repulsion)

        # --- Repulsion obstacles 
        for position in pos_obstacles:
            distance = (self.location - position).magnitude()
            if distance < RADIUS_OBSTACLES + AVOID_DISTANCE:
                f_repulsion = derivativeBivariate(0.005, 0.005, position, self.location) / SAMPLE_TIME
                #f_repulsion = limit(f_repulsion, self.max_force*1.8)
                self.applyForce(-f_repulsion)

            # Avoids that the drone goes over the obstacle
            if (distance < RADIUS_OBSTACLES + SIZE_DRONE):
                self.velocity *= -1


    def get_state(self):
        return [
            self.location[0],
            self.location[1],
            self.vulnerability,
            self.connectivity,
            self.obstacles[0],
            self.obstacles[1],
            self.neighbors[0],
            self.neighbors[1]
        ]
            

    def draw(self, window):
        """
            Defines shape of Drone and draw it to screen
        """
        # usar sprite para desenhar drone
        pygame.draw.circle(window, BLUE, self.location, radius=SIZE_DRONE, width=20)

